variables:
  if_lookback_window:
    default: 90
  search_event_counts_probabilities_table:
    default: "if_search_event_counts_probabilities"
  search_event_financials_table:
    default: "if_search_event_financials"
  search_event_ctr_table:
    default: "if_search_event_ctr"
  browse_event_counts_probabilities_table:
    default: "if_browse_event_counts_probabilities"
  if_event_metrics_model_table:
    default: "if_event_metrics_model"



  if_elastic_index:
    default: "intelligent-filtering-metrics"

  if_kafka_topic:
    default: ecmde-intelligent-filtering-metrics
  if_schema_key_subject:
    default: ecmde-intelligent-filtering-metrics-key
  if_schema_value_subject:
    default: ecmde-intelligent-filtering-metrics-value