variables:
  atc_lookback_days:
    default: 135
  webstore_key:
    default: 6
  abb_lookback_days:
    default: 135
  abb_rolling_window:
    default: 90

  ltr_destination_catalog:
    default: "dev_ent_silver_db"
  ltr_destination_schema:
    default: "ecmde"
  ltr_source_catalog:
    default: "dev_ent_silver_db"
  ltr_source_schema:
    default: "ecmde"
  ltr_feature_agg_table_name:
    default: "ltr_feature_agg"

  ltr_atc_prices_intermediary_table_name:
    default: "ltr_atc_prices_intermediary"
  ltr_atc_term_dates_intermediary_table_name:
    default: "ltr_atc_term_dates_intermediary"
  ltr_atc_base_table_name:
    default: "ltr_atc_base"
  ltr_atc_global_agg_table_name:
    default: "ltr_atc_global_agg"
  ltr_atc_search_lvl_agg_table_name:
    default: "ltr_atc_search_lvl_agg"
  ltr_atc_bod_price_table_name:
    default: "ltr_atc_bod_price_data"
  ltr_atc_z_score_table_name:
    default: "ltr_atc_zscore"

  ltr_abb_linked_searches_table_name:
    default: "ltr_abb_linked_searches"
  ltr_abb_impressions_agg_table_name:
    default: "ltr_abb_impressions_agg"
  ltr_abb_atc_rate_table_name:
    default: "ltr_abb_atc_rate"
  ltr_abb_order_rate_table_name:
    default: "ltr_abb_order_rate"
  ltr_abb_ctr_table_name:
    default: "ltr_abb_ctr"
  ltr_abb_profit_orders_table_name:
    default: "ltr_abb_profit_orders"
  ltr_abb_positive_profit_rate_table_name:
    default: "ltr_abb_positive_profit_rate"

  ltr_abb_atc_rate_weight:
    default: 1000 # value from ABB. weight for calculating ATC posterior
  ltr_abb_ctr_weight:
    default: 500 # value from ABB. weight for calculating CTR posterior
  ltr_abb_order_rate_weight:
    default: 10000 # value from ABB. weight for calculating Order rate posterior
  ltr_abb_global_avg_prior_weight:
    default: 1 # weight for the global avg for blending query level data
  ltr_abb_atc_time_limit_minutes:
    default: 20 # number minutes allowed between search and ATC event
  ltr_abb_min_total_impressions:
    default: 10 # reduce amount of data by only considering search_term/ecode pairs with a minimum number of impressions


  ltr_elastic_index:
    default: "ltr-features"
  elastic_user_key:
    default: "data_ingestion"

  elastic_host_dev:
    default: "https://dsg-search-dev-east.es.eastus.azure.elastic-cloud.com"
  elastic_password_key_dev:
    default: "ltr-elastic-password"

  elastic_host_prodauth:
    default: "https://dsg-search-prodauth-east.es.eastus.azure.elastic-cloud.com"
  elastic_password_key_prodauth:
    default: "ltr-elastic-prodauth-password"

  elastic_host_qa:
    default: "https://dsg-search-qa-east.es.eastus.azure.elastic-cloud.com"
  elastic_password_key_qa:
    default: "ltr-elastic-password"

  elastic_host_prodeast:
    default: "https://dsg-search-prod-east.es.eastus.azure.elastic-cloud.com"
  elastic_password_key_prodeast:
    default: "ltr-elastic-east-password"

  elastic_host_prodwest:
    default: "https://dsg-search-prod-west2.es.westus2.azure.elastic-cloud.com"
  elastic_password_key_prodwest:
    default: "ltr-elastic-west-password"

  elastic_host_prodeast_reserve:
    default: "https://dsg-search-prod-east-reserve.es.eastus.azure.elastic-cloud.com"
  elastic_password_key_prodeast_reserve:
    default: "ltr-elastic-east-reserve-password"

  elastic_host_prodwest_reserve:
    default: "https://dsg-search-prod-west2-reserve.es.westus2.azure.elastic-cloud.com"
  elastic_password_key_prodwest_reserve:
    default: "ltr-elastic-west-reserve-password"

  ltr_kafka_topic:
    default: ecmde-ltr-features
  ltr_schema_key_subject:
    default: ecmde-ltr-features-key
  ltr_schema_value_subject:
    default: ecmde-ltr-features-value