resources:
  jobs:
    ecmde-ecomp-fedex-tracking-silver:
      name: "FedEx Tracking Silver"

      tags:
        job-type: "silver-merge"
        job-group: "shipping"
        version: ${var.bundle_version}

      timeout_seconds: 12000

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: fedex-tracking-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: true
            policy_id: ${var.job_cluster_policy_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            node_type_id: Standard_D16s_v5
            driver_node_type_id: Standard_D16s_v5
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              "spark.databricks.delta.optimizeWrite.enabled": "true"
              "spark.databricks.delta.autoCompact.enabled": "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}
            cluster_log_conf:
              dbfs:
                destination: "dbfs:/cluster-logs/fedex-tracking-silver"

      tasks:
        - task_key: fedex-tracking-merge-task
          job_cluster_key: fedex-tracking-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "com.oracle.ojdbc:ojdbc8:19.3.0.0"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/shipping/notebooks/fedex_merge_notebook
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: silver
              dbx_merge_watermark_table_name: ${var.ecmde_silver_catalog}.${var.ecmde_silver_schema}.watermarks
              dbx_merge_watermark_catalog_name: ${var.ecmde_silver_catalog}
              dbx_merge_watermark_schema_name: ${var.ecmde_silver_schema}
              dbx_merge_source_table: "sci_rpt.eom_fedex_tracking"
              dbx_merge_destination_catalog: ${var.ecmde_silver_catalog}
              dbx_merge_destination_schema: ${var.ecmde_silver_schema}
              dbx_merge_destination_table: "fedex_tracking"

      schedule:
        quartz_cron_expression: "0 0 12 * * ?"
        timezone_id: "America/New_York"
        pause_status: "UNPAUSED"