resources:
  jobs:
    ecmde-fulfillment-dmd-decomp:
      name: ecmde-fulfillment-dmd-decomp

      tags:
        job-group: fulfillment
        version: ${var.bundle_version}

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE_RUN
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: fulfillment_cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 5
              max_workers: 10
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
              spark.driver.extraJavaOptions: -Doracle.jdbc.timezoneAsRegion=false
              spark.executor.extraJavaOptions: -Doracle.jdbc.timezoneAsRegion=false
            custom_tags: # Tag on DKS Job compute (Mandatory)
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: ecmde-fulfillment-dmd-decomp-task
          job_cluster_key: fulfillment_cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "com.oracle.ojdbc:ojdbc8:19.3.0.0"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/fulfillment/notebooks/dmd_decomp_rpt
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: silver
              ecmde_silver_catalog: ${var.ecmde_silver_catalog}
              ecmde_silver_schema: ${var.ecmde_silver_schema}
              ecomp_catalog: ${var.dmd_decomp_ecomp_catalog}
              ecomp_dim_schema: ${var.ecom_dim_schema}
              entdata_catalog: ${var.entdata_catalog}
              ddw_catalog: ${var.dmd_decomp_ddw_catalog}