resources:
  jobs:
    ecmde-fulfillment-txn-order-sku-dq:
      name: ecmde-fulfillment-txn-order-sku-dq
      tags:
        job-group: "fulfillment"
        version: ${var.bundle_version}

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE_RUN
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN
      job_clusters:
        - job_cluster_key: fmod_cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 5
              max_workers: 10
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
            custom_tags:
              TEAM_CODE: ${var.team_code}
      tasks:
        - task_key: fulfillment-txn-order-sku-dq
          job_cluster_key: fmod_cluster
          libraries:
                - whl: ../../dist/*.whl
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/common/notebooks/dq_runner_notebook
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              dq_run_id: "{{job.run_id}}-fulfillment-txn-order-sku-dq"
              dq_domain: fulfillment
              dq_table_name: txn_order_sku
              dq_source_table: ${var.ecomp_catalog}.ecom_dim.txn_order_sku
              dq_source_filter_expr: "DATE(DATE_LAST_MODIFIED) = CURRENT_DATE()"
              dq_config_table: ${var.dq_config_table}
              dq_result_table: ${var.dq_result_table}
              dq_summary_table: ${var.dq_summary_table}
              dq_fail_on_breach: ${var.dq_fail_on_breach}
              dq_xmatters_webhook_secret: ${var.dq_xmatters_webhook_secret}
