resources:
  jobs:
    Run_ECOM_Rekeyer:
      name: "Run ECOM Rekeyer"

      permissions:
      - group_name: ${var.admin_group_name}
        level: CAN_MANAGE
      - group_name: g_ddp_vendor_databricks
        level: CAN_MANAGE
      - group_name: ${var.eng_group_name}
        level: CAN_MANAGE_RUN
      - service_principal_name: ${var.data_platform_sp_id}
        level: CAN_MANAGE_RUN
      - group_name: ${var.l2_support_group_name}
        level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: Rekey_Cluster
          new_cluster:
            cluster_name: ""
            spark_version: 16.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.ml_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_E8ads}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
              spot_bid_max_price: -1
            spark_env_vars:
              PYSPARK_PYTHON: /databricks/python3/bin/python3
            enable_elastic_disk: true
            data_security_mode: SINGLE_USER
            runtime_engine: PHOTON
            num_workers: 2
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: Clone_Prod_Tables
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/2b.  Sync Tables (only Non-Prod)
            source: WORKSPACE
          disable_auto_optimization: true
        - task_key: Record_Starting_Versions
          depends_on:
            - task_key: Clone_Prod_Tables
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/2c.  Record Table Versions
            source: WORKSPACE
          disable_auto_optimization: true
        - task_key: Clear_Existing_Rekeyer_Objects
          depends_on:
            - task_key: Record_Starting_Versions
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/2d.  Clear Existing Rekeyer Objects
            source: WORKSPACE
          disable_auto_optimization: true
        - task_key: Warm_Cluster
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/0. Start Cluster
            source: WORKSPACE
          job_cluster_key: Rekey_Cluster
          libraries:
            - maven:
                coordinates: com.oracle.ojdbc:ojdbc8:19.3.0.0
        - task_key: Generate_Rekeyer_Mapping_Tables
          depends_on:
            - task_key: Clear_Existing_Rekeyer_Objects
            - task_key: Warm_Cluster
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/3a. Rekeyer - Generate Mapping
            source: WORKSPACE
          job_cluster_key: Rekey_Cluster
          libraries:
            - maven:
                coordinates: com.oracle.ojdbc:ojdbc8:19.3.0.0
        - task_key: Rekey_All_Tables
          depends_on:
            - task_key: Generate_Rekeyer_Mapping_Tables
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/3b. Rekeyer - Rekey Tables
            source: WORKSPACE
          disable_auto_optimization: true
        - task_key: Rollback_on_Error
          depends_on:
            - task_key: Generate_Rekeyer_Mapping_Tables
            - task_key: Rekey_All_Tables
          run_if: AT_LEAST_ONE_FAILED
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/rekeyer/notebooks/99.  Rollback Table Versions
            source: WORKSPACE
          disable_auto_optimization: true

      queue:
        enabled: false
      parameters:
        - name: ecom_catalog
          default: dev_ecmde_db
        - name: test_schema
          default: rekeyer_test
        - name: run_id
          default: "{{job.run_id}}"
      performance_target: PERFORMANCE_OPTIMIZED
