resources:
  jobs:
    ecmde-inventory-ecode-attributes-es-ingest:
      name: "ecmde-inventory-ecode-attributes-es-ingest"

      tags:
        job-group: "inventory"
        version: ${var.bundle_version}

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE_RUN
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: inv-es-ingest-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            driver_instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 1
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: ecode-attributes-es-ingest-task
          job_cluster_key: inv-es-ingest-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "org.elasticsearch:elasticsearch-spark-30_2.12:8.17.2"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/inventory/notebooks/ecode_attributes_es_ingest_notebook
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              es_host: ${var.inv_es_host}
              es_port: ${var.inv_es_port}
              es_user: ${var.inv_es_user}
              es_password_key: ${var.inv_es_password_key}
              es_kv_scope: ${var.inv_es_kv_scope}
              es_index: ${var.inv_ecode_attributes_index}
              destination_catalog: ${var.inv_destination_catalog}
              destination_schema: ${var.inv_destination_schema}
              destination_table: ${var.inv_ecode_attributes_table_name}
