resources:
  jobs:
    ecmde-ecomp-lineup-dbx-rpt-dly-egress:
      name: ecmde-ecomp-lineup-dbx-rpt-dly-egress

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDM001"
        cm-job-name: "OMNIPRDDM001_010"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: dbx_rpt_dly_egress
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/mysql_dbx_egress_dly
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}

    ecmde-ecomp-lineup-cwl-dim-load:
      name: cmde-ecomp-lineup-cwl-dim-load

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_010"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: cwl_dim_load
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/lineup_cwl_hrchy_vndr_load
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}

    ecmde-ecomp-lineup-mysql-hist-egress:
      name: ecmde-ecomp-lineup-mysql-hist-egress

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_020"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: mysql_hist_egress
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/dbx_mysql_egress_hist
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}

    ecmde-ecomp-lineup-mysql-cws-stg-load:
      name: ecmde-ecomp-lineup-mysql-cws-stg-load

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_030"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: mysql-cws-stg-load
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/lineup_cws_stg_load_inv_po
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}
    ecmde-ecomp-lineup-mysql-pmms-stg-load:
      name: ecmde-ecomp-lineup-mysql-pmms-stg-load

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_040"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: mysql-pmms-stg-load
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/lineup_pmms_stg_load_all
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}

    ecmde-ecomp-lineup-mysql-cws-sp:
      name: ecmde-ecomp-lineup-mysql-cws-sp

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_050"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: mysql-cws-sp
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/mysql_lineup_cws_sp_ups
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}

    ecmde-ecomp-lineup-mysql-pmms-sp:
      name: ecmde-ecomp-lineup-mysql-pmms-sp

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_060"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: mysql-pmms-sp
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/mysql_lineup_pmms_sp_ups
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}
    ecmde-ecomp-lineup-mysql-dly-egress:
      name: ecmde-ecomp-lineup-mysql-dly-egress

      tags:
        cm-application: "OMNI"
        cm-sub-application: "PRD"
        cm-job-folder: "OMNIPRDDY001"
        cm-job-name: "OMNIPRDDY001_070"

      permissions:
        - group_name: ${var.admin_group_name}
          level: CAN_MANAGE
        - group_name: ${var.eng_group_name}
          level: CAN_MANAGE
        - service_principal_name: ${var.ecmde_sp_id}
          level: CAN_MANAGE
        - group_name: ${var.l2_support_group_name}
          level: CAN_MANAGE_RUN
        - service_principal_name: ${var.data_platform_sp_id}
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: lineup-mysql-cluster
          new_cluster:
            spark_version: 15.4.x-scala2.12
            apply_policy_default_values: false
            policy_id: ${var.job_cluster_policy_id}
            instance_pool_id: ${var.instance_pool_id}
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
            data_security_mode: USER_ISOLATION
            runtime_engine: STANDARD
            autoscale:
              min_workers: 2
              max_workers: 5
            spark_conf:
              workspace_path_prefix: ${var.workspace_path_prefix}
              spark.databricks.delta.optimizeWrite.enabled: "true"
              spark.databricks.delta.autoCompact.enabled: "true"
            custom_tags:
              TEAM_CODE: ${var.team_code}

      tasks:
        - task_key: mysql_dly_egress
          job_cluster_key: lineup-mysql-cluster
          libraries:
            - whl: ../../dist/*.whl
            - maven:
                coordinates: "mysql:mysql-connector-java:8.0.33"
          notebook_task:
            notebook_path: ${var.workspace_path_prefix}/src/ecmde_ecomm/ecomp/notebooks/lineup/dbx_mysql_egress_dly
            base_parameters:
              azure_kv_scope: ${var.azure_kv_scope}
              workspace_path_prefix: ${var.workspace_path_prefix}
              dbx_env: ${var.dbx_env}
              dbx_user_id: ${workspace.current_user.short_name}
              dbx_data_quality: ecomp
              lineup_mysql_jdbc_url: ${var.lineup_mysql_jdbc_url}
              lineup_mysql_jdbc_host: ${var.lineup_mysql_jdbc_host}
              ecomp_catalog: ${var.ecomp_catalog}
    