name: Deploy to Databricks Bundle to DEV Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.4'

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test.yml
    secrets: inherit

  migrations:
    name: "DEV: Apply Migrations"
    needs: [ build-and-test ]
    uses: ./.github/workflows/develop-migrations.yml
    secrets: inherit

  deploy:
    name: "Development: Deploy Databricks Bundle"
    runs-on: [self-hosted, azure]
    needs: [build-and-test, migrations]
    steps:
      - name: "Vault: Get Databricks Secrets"
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.tools.dcsg.com
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            concourse/data-e-commerce/databricks/non-prod clientId | ARM_CLIENT_ID;
            concourse/data-e-commerce/databricks/non-prod clientSecret | ARM_CLIENT_SECRET;
            concourse/data-e-commerce/databricks/non-prod tenantId | ARM_TENANT_ID;

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK.
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Setup DBX CLI
        uses: databricks/setup-cli@main

      - name: Deploy DBX Bundle
        run: |
          set -e
          pip install ".[dev]"
          databricks bundle deploy -t development
        env:
          DATABRICKS_BUNDLE_ENV: development