create table if not exists ${common_schema}.watermarks
(
    catalog_name string not null COMMENT 'The catalog of the destination table that is being incrementally updated.',
    schema_name string not null COMMENT 'The schema name of the destination table that is being incrementally updated.',
    table_name string not null  COMMENT 'The destination table name that is being incrementally updated.',
    watermark_epoch_sec_utc bigint COMMENT 'The watermark timestamp in UTC tz that is the last time we fetched data for the destination table',
    constraint watermark_pk primary key (catalog_name, schema_name, table_name)
)  COMMENT 'This table acts as a watermark indicator for incrementally fetching data from one or more source tables into a destination table. This table is used internally by the E-Commerce Data Engineering team.';


create table if not exists ${co_stage_schema}.order_message_cancel
(
    message_key string not null,
    message_dttm timestamp not null,
    gold_created_by string not null,
    gold_created_on_utc timestamp not null,
    cancel_source string,
    cancel_agent string,
    cancel_dttm timestamp,
    cancel_reason string,
    order_number string,
    order_state string,
    order_source string,
    order_channel string,
    aosstorenumber string,
    order_type string,
    order_placed_dttm timestamp,
    order_last_update_dttm timestamp,
    identity_id string,
    auth_id string,
    loyalty_acct_id string,
    address1 string,
    address2 string,
    address3 string,
    city string,
    state string,
    zip string,
    country string,
    reward_cert_codes string,
    sku string,
    external_item_id string,
    order_line_num string,
    order_line_unit_seq string,
    order_line_state string,
    order_line_last_update_dttm timestamp,
    original_price string,
    discount string,
    purchase_price string,
    est_unit_tax string,
    upc string,
    est_delivery_date timestamp,
    guarenteedtogetthere_date timestamp,
    line_item_type string,
    ship_sku string,
    ship_upc string,
    ship_mode string,
    ship_location_id string,
    ship_carrier string,
    ship_class string,
    original_ship_charge string,
    ship_discount string,
    ship_charge string,
    ship_address1 string,
    ship_address2 string,
    ship_address3 string,
    ship_city string,
    ship_state string,
    ship_zip string,
    tax_product_code string,
    est_ship_tax_shp_dtl string,
    date_added timestamp,
    unit_cancel_source string,
    unit_cancel_dttm timestamp,
    unit_cancel_reason string,
    constraint order_message_cancel_pk primary key (
         order_number,
         order_source,
         order_state,
         order_line_state,
         order_channel,
         sku,
         order_line_num,
         order_line_unit_seq
    )
)
    cluster by (gold_created_on_utc, order_placed_dttm, cancel_dttm, cancel_source)
    comment 'This table records orders that have been cancelled.';


create table if not exists ${co_stage_schema}.order_message_placed
(
    message_key string not null,
    message_dttm timestamp not null,
    gold_created_by string not null,
    gold_created_on_utc timestamp not null,
    order_number string,
    order_state string,
    order_source string,
    order_channel string,
    aosstorenumber string,
    order_type string,
    order_placed_dttm timestamp,
    order_last_update_dttm timestamp,
    identity_id string,
    auth_id string,
    loyalty_acct_id string,
    address1 string,
    address2 string,
    address3 string,
    city string,
    state string,
    zip string,
    country string,
    reward_cert_codes string,
    sku string,
    external_item_id string,
    order_line_num string,
    order_line_unit_seq string,
    order_line_state string,
    order_line_last_update_dttm timestamp,
    original_price string,
    discount string,
    purchase_price string,
    est_unit_tax string,
    upc string,
    est_delivery_date timestamp,
    guarenteedtogetthere_date timestamp,
    line_item_type  string,
    ship_sku string,
    ship_upc string,
    ship_mode string,
    ship_location_id string,
    ship_carrier string,
    ship_class string,
    original_ship_charge string,
    ship_discount string,
    ship_charge string,
    ship_address1 string,
    ship_address2 string,
    ship_address3 string,
    ship_city string,
    ship_state string,
    ship_zip string,
    tax_product_code string,
    est_ship_tax_shp_dtl string,
    date_added timestamp,
    constraint order_message_placed_pk primary key (
        order_number,
        order_source,
        order_state,
        order_line_state,
        order_channel,
        sku,
        order_line_num,
        order_line_unit_seq
    )
)
    cluster by (gold_created_on_utc, order_state, sku)
    comment 'This table records orders placed and the state of those orders.';

create table if not exists ${sb_load_schema}.stg_nrt_inventory
(
    item_id string not null comment "A product sku code.",
    store_id int not null comment "The location ID associated to the sku inventory record.",
    atp_inventory_qty int not null comment "The Available to Promise quantity available for the sku at this store location.",
    create_date timestamp not null comment "The UTC timestamp of when the inventory was updated for this sku and location."
)
    cluster by (store_id, item_id, create_date)
    comment 'This table records atp inventory quantities by sku, store, and the time at which the inventory was updated.';

CREATE TABLE IF NOT EXISTS ${co_stage_schema}.order_message_discount (
    message_key STRING NOT NULL,
    message_dttm TIMESTAMP NOT NULL,
    gold_created_by STRING NOT NULL,
    gold_created_on_utc TIMESTAMP NOT NULL,
    order_number STRING,
    external_item_id STRING,
    order_line_unit_seq STRING,
    discount STRING,
    applicable_discount_amount STRING,
    discount_level STRING,
    discount_name STRING,
    discount_desc STRING,
    cart_desc STRING,
    discount_ext_id STRING,
    discount_type STRING,
    discount_code STRING,
    discount_applied_dttm TIMESTAMP,
    date_added TIMESTAMP,
    CONSTRAINT co_stage_order_message_discount_pk PRIMARY KEY (
        order_number,
        order_line_unit_seq,
        external_item_id,
        discount_level,
        discount_name,
        discount_ext_id,
        discount_type
    )
)
CLUSTER BY (gold_created_on_utc, external_item_id)
COMMENT 'Gold table for discounts applied at the order line level.';

create table if not exists ${sb_load_schema}.stg_kafka_eat_chain_atp
(
    item_id string not null comment "A product sku code.",
    store_id string not null comment "The location ID associated to sku inventory record.",
    bopis_atp_qty int not null comment "The Available to Promise quantity available for the sku at this specified location.",
    isa_qty int not null comment "The ISA Quantity is the on-hand inventory that is available for in-store purchase for the specified store location.",
    bopl_qty int not null comment "The Buy Online Pickup Later quantity on-hand inventory that is available at this store location.",
    is_deleted boolean not null comment "A flag indicating that the inventory record has been soft deleted indicating that inventory across all programs has been depleted.",
    date_last_modified_eom timestamp not null comment "The timestamp of when the inventory was updated for this sku and location.",
    date_added timestamp not null comment "The timestamp of when this record was inserted into the datalake.",
    message_timestamp timestamp not null comment "The Kafka message timestamp when the message was delivered to the source topic.",
    `partition` int not null comment "The Kafka partition this record was published to.",
    offset int not null comment "The Kafka offset within the partition for the published message."
)
    cluster by (item_id, store_id, date_last_modified_eom, date_added)
    comment 'This table holds data from Kafka for the eat-chain-atp topic.';


create table if not exists ${co_stage_schema}.order_message_placed_payment
(
    message_key string not null,
    message_dttm timestamp not null,
    order_number string,
    order_last_update_dttm timestamp,
    payment_type string,
    card_number string,
    authorized_amount string,
    date_added timestamp,
    ecomp_created_by string not null,
    ecomp_created_on_utc timestamp not null,
    ecomp_updated_by string not null,
    ecomp_updated_on_utc timestamp not null,
    constraint order_message_placed_payment_pk primary key(
        order_number,
        payment_type
    )
)
    cluster by (order_number, date_added, order_last_update_dttm, ecomp_created_by);

CREATE TABLE IF NOT EXISTS ${co_stage_schema}.order_message_fulfill (
    message_key STRING NOT NULL,
    message_dttm TIMESTAMP NOT NULL,
    gold_created_by STRING NOT NULL,
    gold_created_on_utc TIMESTAMP NOT NULL,
    order_number STRING,
    order_state STRING,
    order_source STRING,
    order_type STRING,
    order_placed_dttm TIMESTAMP,
    order_last_update_dttm TIMESTAMP,
    sku STRING,
    external_item_id STRING,
    order_line_num STRING,
    order_line_unit_seq STRING,
    order_line_state STRING,
    order_line_last_update_dttm TIMESTAMP,
    purchase_price STRING,
    return_price STRING,
    est_unit_tax STRING,
    est_delivery_date TIMESTAMP,
    start_est_delivery_date TIMESTAMP,
    guarenteedtogetthere_date TIMESTAMP,
    line_item_type STRING,
    fulfillment_type STRING,
    purchase_order STRING,
    fulfill_location_id STRING,
    fulfill_address1 STRING,
    fulfill_address2 STRING,
    fulfill_address3 STRING,
    fulfill_city STRING,
    fulfill_state STRING,
    fulfill_zip STRING,
    fulfill_order_id STRING,
    fulfill_shipped_dttm TIMESTAMP,
    ship_sku STRING,
    ship_upc STRING,
    ship_mode STRING,
    ship_location_id STRING,
    ship_carrier STRING,
    ship_class STRING,
    ship_tracking_num STRING,
    ship_charge STRING,
    ship_address1 STRING,
    ship_address2 STRING,
    ship_address3 STRING,
    ship_city STRING,
    ship_state STRING,
    ship_zip STRING,
    tax_product_code STRING,
    est_ship_tax_shp_dtl STRING,
    return_tracking_num STRING,
    return_reason STRING,
    return_location STRING,
    return_dttm TIMESTAMP,
    return_label_creation_date TIMESTAMP,
    return_unreceipted STRING,
    return_fraud_check_id STRING,
    return_pickup_date TIMESTAMP,
    return_delivery_date TIMESTAMP,
    return_process_date TIMESTAMP,
    return_source STRING,
    unit_cancel_source STRING,
    unit_cancel_dttm TIMESTAMP,
    unit_cancel_reason STRING,
    date_added TIMESTAMP,
    CONSTRAINT co_order_message_fulfill_pk PRIMARY KEY (
         order_number,
         order_source,
         order_state,
         order_line_state,
         sku,
         order_line_num,
         order_line_unit_seq
    )
)
cluster by (gold_created_on_utc, order_state, order_source)
COMMENT 'This table records order fulfillment and shipment details, including cancellations and returns.';



CREATE TABLE if not exists ${ecom_dim_schema}.payment_method 
( PAYMENT_METHOD_KEY BIGINT NOT NULL, PAYMENT_METHOD_CODE STRING, 
PAYMENT_METHOD_DESC STRING, DATA_SOURCE_KEY BIGINT NOT NULL DEFAULT -1,
 IS_CURRENT STRING NOT NULL DEFAULT 'C', DATE_ADDED TIMESTAMP NOT NULL DEFAULT
  current_timestamp(), ADDED_BY STRING NOT NULL DEFAULT current_user(),
   DATE_LAST_MODIFIED TIMESTAMP, MODIFIED_BY STRING, RECORD_STATUS STRING NOT NULL DEFAULT 'A',
    WEB_OPS_TNDR_METHOD STRING, CO_PAYMENT_TYPE STRING, 
    CONSTRAINT `payment_method_pk` PRIMARY KEY (`PAYMENT_METHOD_KEY`)) USING delta TBLPROPERTIES ( 'delta.enableDeletionVectors' = 'true', 'delta.feature.allowColumnDefaults' = 'supported', 'delta.feature.deletionVectors' = 'supported', 'delta.feature.invariants' = 'supported', 'delta.minReaderVersion' = '3', 'delta.minWriterVersion' = '7');


CREATE TABLE  if not exists ${ecom_dim_schema}.date_dim (
  DATE_KEY BIGINT NOT NULL,
  DATE_ID BIGINT NOT NULL,
  DATE_CODE DATE,
  CALENDAR_DATE TIMESTAMP_NTZ,
  DATE_ID_LY BIGINT,
  DATE_ID_LLY BIGINT,
  FISCAL_DAY_IN_WEEK BIGINT,
  FISCAL_DAY_IN_MONTH BIGINT,
  FISCAL_DAY_IN_SEASON BIGINT,
  FISCAL_DAY_IN_QUARTER BIGINT,
  FISCAL_DAY_IN_YEAR BIGINT,
  FISCAL_DAY_NAME STRING,
  FISCAL_DAY_NAME_ABB STRING,
  FISCAL_DAY_PRIOR STRING,
  FISCAL_WEEK_IN_MONTH BIGINT,
  FISCAL_WEEK_IN_QUARTER BIGINT,
  FISCAL_WEEK_IN_SEASON BIGINT,
  FISCAL_WEEK_IN_YEAR BIGINT,
  FISCAL_WEEK_BEGIN_DATE BIGINT,
  FISCAL_WEEK_END_DATE BIGINT,
  FISCAL_YEAR_WEEK BIGINT,
  FISCAL_YEAR_WEEK_PRIOR BIGINT,
  FISCAL_YEAR_WEEK_2WA BIGINT,
  FISCAL_YEAR_WEEK_3WA BIGINT,
  FISCAL_MONTH_IN_YEAR BIGINT,
  FISCAL_MONTH_IN_SEASON BIGINT,
  FISCAL_MONTH_IN_QUARTER BIGINT,
  FISCAL_MONTH_BEGIN_DATE BIGINT,
  FISCAL_MONTH_END_DATE BIGINT,
  FISCAL_MONTH_NAME STRING,
  FISCAL_MONTH_NAME_ABB STRING,
  FISCAL_YEAR_MONTH BIGINT,
  FISCAL_YEAR_MONTH_PRIOR BIGINT,
  FISCAL_QUARTER_IN_SEASON BIGINT,
  FISCAL_QUARTER_IN_YEAR BIGINT,
  FISCAL_QUARTER_BEGIN_DATE BIGINT,
  FISCAL_QUARTER_END_DATE BIGINT,
  FISCAL_QUARTER_NAME STRING,
  FISCAL_QUARTER_NAME_ABB STRING,
  FISCAL_YEAR_QUARTER BIGINT,
  FISCAL_YEAR_QUARTER_PRIOR BIGINT,
  FISCAL_SEASON_IN_YEAR BIGINT,
  FISCAL_SEASON_BEGIN_DATE BIGINT,
  FISCAL_SEASON_END_DATE BIGINT,
  FISCAL_SEASON_NAME STRING,
  FISCAL_SEASON_NAME_ABB STRING,
  FISCAL_YEAR_SEASON BIGINT,
  FISCAL_YEAR_SEASON_PRIOR BIGINT,
  FISCAL_YEAR BIGINT,
  FISCAL_YEAR_BEGIN_DATE BIGINT,
  FISCAL_YEAR_END_DATE BIGINT,
  FISCAL_PRIOR_YEAR_COMP_WEEK BIGINT,
  HOLIDAY STRING,
  WEEKDAY_INDICATOR STRING,
  DAYLIGHT_SAVINGS_INDICATOR STRING,
  RECORD_STATUS STRING,
  DATE_ID_TY BIGINT,
  FISCAL_YEAR_WEEK_TY BIGINT,
  FISCAL_YEAR_MONTH_TY BIGINT,
  FISCAL_YEAR_QUARTER_TY BIGINT,
  FISCAL_YEAR_SEASON_TY BIGINT,
  FISCAL_YEAR_TY BIGINT,
  KEY_DATE_INDICATOR BIGINT,
  DATE_ID_LLLY BIGINT,
  DATE_ID_LLLLY BIGINT,
  CONSTRAINT `date_dim_pk` PRIMARY KEY (`DATE_KEY`))
USING delta
TBLPROPERTIES (
  'delta.columnMapping.mode' = 'name',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.columnMapping' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.timestampNtz' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7');

CREATE TABLE if not exists ${ecom_dim_schema}.fulfillment_mode (
    FULFILLMENT_MODE_KEY BIGINT NOT NULL,
    FULFILLMENT_MODE_CODE STRING NOT NULL,
    FULFILLMENT_MODE_DESC STRING NOT NULL,
    SHIP_RANGE_KEY BIGINT NOT NULL DEFAULT -1,
    DATA_SOURCE_KEY BIGINT NOT NULL DEFAULT -1,
    CHAIN_KEY BIGINT NOT NULL DEFAULT -1,
    IS_CURRENT STRING NOT NULL DEFAULT 'C',
    DATE_ADDED TIMESTAMP NOT NULL DEFAULT current_timestamp(),
    ADDED_BY STRING NOT NULL DEFAULT current_user(),
    DATE_LAST_MODIFIED TIMESTAMP,
    MODIFIED_BY STRING,
    RECORD_STATUS STRING NOT NULL DEFAULT 'A',
    REFERENCE_ID BIGINT,
    CARRIER_KEY BIGINT,
    SHIPPING_DEFINITION STRING,
    SCI_SERVICE_LEVEL_ID BIGINT,
    SERVICE_LEVEL STRING,
    SERVICE_LEVEL_DESCRIPTION STRING,
    SHIP_MODE STRING,
    SHIP_CLASS STRING,
    CONSTRAINT `fulfillment_mode_pk` PRIMARY KEY (`FULFILLMENT_MODE_KEY`))
    USING delta
    TBLPROPERTIES (
        'delta.enableDeletionVectors' = 'true',
        'delta.feature.allowColumnDefaults' = 'supported',
        'delta.feature.deletionVectors' = 'supported',
        'delta.feature.invariants' = 'supported',
        'delta.minReaderVersion' = '3',
        'delta.minWriterVersion' = '7');

CREATE TABLE ${ecom_dim_schema}.order_sku (
      ORDER_SKU_KEY BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      CHAIN_KEY BIGINT NOT NULL,
      WEB_ORD_NUM BIGINT NOT NULL,
      DKS_SKU BIGINT NOT NULL,
      WEB_SKU BIGINT NOT NULL,
      PID BIGINT NOT NULL,
      ORDER_LINE_CNT BIGINT,
      ORDER_SKU_STATUS_KEY BIGINT,
      ORDER_SKU_STATUS_DTTM TIMESTAMP,
      ORDER_LINE_TYPE_KEY BIGINT,
      ORIG_TOT_UNITS BIGINT,
      ORIG_TOT_AMT DOUBLE,
      ORIG_TOT_EXTENDED_AMT DECIMAL(12,2),
      ORIG_TOT_FREIGHT_AMT DECIMAL(12,2),
      ORIG_TOT_TAX_AMT DECIMAL(12,2),
      CURRENT_COST DOUBLE,
      AVERAGE_COST DOUBLE,
      WEB_PRICE DOUBLE,
      CLEARANCE_TYPE_KEY BIGINT,
      PROMISE_DATE BIGINT,
      FINAL_TOT_UNITS BIGINT,
      FINAL_TOT_AMT DOUBLE,
      FINAL_TOT_EXTENDED_AMT DECIMAL(12,2),
      FINAL_TOT_FREIGHT_AMT DECIMAL(12,2),
      FINAL_TOT_TAX_AMT DECIMAL(12,2),
      ORDER_HEADER_KEY BIGINT NOT NULL,
      ORDER_DATE_KEY BIGINT NOT NULL,
      ORDER_TIME_KEY DOUBLE NOT NULL,
      WEBSTORE_ORDER_DATE STRING,
      STYLE_KEY BIGINT NOT NULL,
      DKS_SKU_KEY BIGINT NOT NULL,
      WEB_SKU_KEY BIGINT NOT NULL,
      PRODUCT_KEY BIGINT NOT NULL,
      DATA_SOURCE_KEY BIGINT NOT NULL,
      DATE_ADDED TIMESTAMP NOT NULL DEFAULT current_timestamp(),
      ADDED_BY STRING NOT NULL DEFAULT current_user(),
      DATE_LAST_MODIFIED TIMESTAMP DEFAULT current_timestamp(),
      MODIFIED_BY STRING,
      RECORD_STATUS STRING NOT NULL DEFAULT 'A',
      REFERENCE_ID BIGINT,
      CHANNEL_TYPE_KEY BIGINT,
      ORDER_FULFILL_NUMBER DECIMAL(38,3),
      PO_NUMBER STRING,
      SHIP_TO_STATE STRING,
      SHIP_TO_ZIP STRING,
      CUST_FULFILLMENT_MODE_KEY BIGINT,
      ORIG_TOT_EXT_DISC_AMT DOUBLE,
      ORIG_TOT_FREIGHT_DISC_AMT DOUBLE,
      PRESALE_FLG BIGINT,
      HOT_MARKET_FLG BIGINT,
      PICK_DECLINE_CNT BIGINT,
      GTGT_IND BIGINT,
      CARRIER_FREIGHT_COST DOUBLE,
      NUM_BOXES_FULFILLED BIGINT,
      NUM_BOXES_EXPENSED BIGINT,
      NUM_BOXES_DELIVERED BIGINT,
      MARGIN_DECOMP_CLASSIFICATION BIGINT,
      FINAL_AMT_UPD_KEY BIGINT,
      MIN_DO_CREATE_DTTM TIMESTAMP,
      ACTUAL_FF_CHANNEL_KEY BIGINT,
      ACTUAL_FF_LOCATION_CNT BIGINT,
      CLR_COLOR_CODE STRING,
      DAY_PERM_PRICE DOUBLE,
      PO_BOX_CD STRING,
      BOPIS_SAVE_THE_SALE_FLG STRING,
      BOPIS_STORE STRING,
      GTGT_DATE TIMESTAMP,
      CONSTRAINT `order_sku_pk` PRIMARY KEY (`ORDER_SKU_KEY`))
    USING delta
    TBLPROPERTIES (
        'delta.checkpoint.writeStatsAsJson' = 'false',
        'delta.checkpoint.writeStatsAsStruct' = 'true',
        'delta.enableDeletionVectors' = 'true',
        'delta.feature.allowColumnDefaults' = 'supported',
        'delta.feature.appendOnly' = 'supported',
        'delta.feature.deletionVectors' = 'supported',
        'delta.feature.identityColumns' = 'supported',
        'delta.feature.invariants' = 'supported',
        'delta.minReaderVersion' = '3',
        'delta.minWriterVersion' = '7');
