CREATE TABLE IF NOT EXISTS ${ecom_schema}.stg_oso_order_fulfill (

    order_fulfill_number     BIGINT       NOT NULL COMMENT 'Composite of order_id, ".00", and fr_sequence_number',
    chain_key                STRING                         ,
    fulfillment_status_cd    STRING       COMMENT 'Fulfillment status code. See prod_oso_db.oso_ref.item_status',
    fulfillment_status_dttm  TIMESTAMP    COMMENT 'UTC timestamp when OSO last updated this record in Newman (nmn_updated_timestamp)',
    fulfillment_date_key     BIGINT       COMMENT 'UTC timestamp when package was marked fulfilled (package_ship_timestamp) as YYYYMMDD numeric',
    channel_type_key         INT                            ,
    fulfillment_location_cd  BIGINT       COMMENT 'Facility number where item will be sourced (source_facility_number)',
    store_key                BIGINT       COMMENT 'Facility number where item will be sourced (source_facility_number)',
    shipment_type_cd         STRING,
    carrier_key              BIGINT                         ,
    fulfillment_mode_key     BIGINT                         ,
    promise_date_key         INT          COMMENT 'Latest promise date presented to Athlete (promise_end_date) as YYYYMMDD numeric',
    ship_state               STRING                         ,
    ship_zip                 STRING       COMMENT 'Destination zip code as defined by Athlete Order (destination_zip)',
    web_ord_num              BIGINT       COMMENT 'Customer order number as defined by Athlete Order (order_id)',
    vendor_key               BIGINT       COMMENT 'Facility number where item will be sourced (source_facility_number)',
    ship_method              STRING                         ,
    do_create_dttm           TIMESTAMP    COMMENT 'UTC timestamp when OSO determined a source (sourced_timestamp)',
    po_number                STRING       COMMENT 'Purchase order number generated by Vendor Fulfillment Technology (po_number)',
    min_fulfillment_dttm     TIMESTAMP                      ,
    date_last_modified       TIMESTAMP                      ,
    modified_by              STRING                         ,
    CONSTRAINT stg_oso_order_fulfill_pk1 PRIMARY KEY (order_fulfill_number)
)
CLUSTER BY (order_fulfill_number)
COMMENT 'Table storing athlete order fulfillment details';



CREATE TABLE IF NOT EXISTS ${ecom_schema}.stg_oso_order_sku_shipment (

    order_sku_shipment_key    BIGINT    COMMENT 'Surrogate record key (not  part of PK)',

    fulfillment_date_key      BIGINT    COMMENT 'YYYYMMDD of the shipment event',
    fulfillment_location_cd   BIGINT    COMMENT 'Facility number where SKU was shipped (newman_item.source_facility_number)',
    shipped_units             BIGINT    COMMENT 'Quantity of the SKU shipped',
    webstore_key              BIGINT    COMMENT 'FK to webstore dimension (if applicable)',
    tracking_number           STRING    COMMENT 'Carrier tracking number for this shipment',

    dks_sku                   BIGINT    NOT NULL COMMENT 'SKU identifier from Newman item (newman_item.sku)',
    sci_lpn_id                BIGINT     COMMENT 'SCI LPN identifier (sci_rpt_eom_fedex_tracking.dtl_lpn_id)',

    order_fulfill_number      BIGINT    COMMENT 'Composite of order_id + zero-padded 4-digit sequence (e.g. 0001 → 123450001)',
    eom_shipped_dttm          TIMESTAMP COMMENT 'Timestamp when EOM marked this order shipped',
    web_ord_num               BIGINT    NOT NULL COMMENT 'Customer order number (newman_item.order_id)',

    date_last_modified        TIMESTAMP COMMENT 'Source update timestamp, e.g. silver_layer_update_timestamp',
    modified_by               STRING    COMMENT 'Process or user that last modified this record, e.g. "OSOSilver"',

    CONSTRAINT stg_oso_order_sku_shipment_pk
        PRIMARY KEY (order_sku_shipment_key)
)
CLUSTER BY (order_sku_shipment_key)
COMMENT 'Per-SKU shipment details for each order';

CREATE TABLE IF NOT EXISTS ${ecom_schema}.stg_oso_order_header (
    web_ord_num         STRING     NOT NULL COMMENT 'Customer order number (newman_item.order_id)',
    chain_key           STRING,
    order_status_dttm   TIMESTAMP   NOT NULL,
    order_status_key    STRING NOT NULL,
    date_last_modified  TIMESTAMP   NOT NULL COMMENT 'Source update timestamp, e.g. silver_layer_update_timestamp',
    modified_by         STRING NOT NULL COMMENT 'Process or user that last modified this record, e.g. "OSOSilver"',

    CONSTRAINT pk_order_header PRIMARY KEY (web_ord_num)
);

CREATE TABLE IF NOT EXISTS ${ecom_schema}.stg_oso_order_delivery
(
    order_delivery_key         STRING   NOT NULL COMMENT 'Unique identifier for the order delivery record',
    webstore_key               BIGINT,

    package_type_id            BIGINT,
    sci_lpn_id                 BIGINT,
    tracking_number            STRING  COMMENT 'Shipment tracking number',
    delivery_status_cd         STRING,
    fulfillment_date_key       BIGINT,
    fulfillment_location_cd    BIGINT,
    actual_shipped_dttm        TIMESTAMP,
    shipped_qty                BIGINT,
    package_type_descr         STRING,
    ship_via                   STRING,
    carrier_key                BIGINT,
    fulfillment_mode_key       BIGINT COMMENT 'Identifier for the fulfillment mode',
    order_fulfill_number       BIGINT COMMENT 'Composite order-fulfill number',
    web_ord_num                BIGINT  COMMENT 'Athlete/web order number',
    lpn_create_dttm            TIMESTAMP,
    date_last_modified_utc     TIMESTAMP  COMMENT 'Last modified in source system',
    modified_by                STRING   NOT NULL COMMENT 'Hard-coded value indicating update source: "OSOSilver"',

    CONSTRAINT order_delivery_pk PRIMARY KEY (order_delivery_key)
)
CLUSTER BY (web_ord_num, order_delivery_key)
COMMENT 'OSO staging table storing order delivery details.';


CREATE TABLE IF NOT EXISTS ${ecom_schema}.stg_oso_order_sku (
    web_ord_num      BIGINT   NOT NULL COMMENT 'Athlete order number',
    sku                       BIGINT   NOT NULL COMMENT 'A product sku code',
    order_sku_status_key      BIGINT,
    po_number                 BIGINT,
    min_do_create_dttm_utc    TIMESTAMP,
    chain_key        BIGINT,
    order_sku_status_dttm     TIMESTAMP,
    date_last_modified_utc    TIMESTAMP  COMMENT 'Last modified date pulled from oso/newman_item.',
    modified_by               STRING     COMMENT 'Hard‑coded value indicating update source: "OSOSilver"',

    CONSTRAINT fulfillment_order_sku_pk PRIMARY KEY (web_ord_num, sku)
)
COMMENT 'OSO staging table storing line item details about the athlete order.'
CLUSTER BY (sku, web_ord_num);

CREATE TABLE IF NOT EXISTS ${ecom_schema}.stg_oso_txn_order_sku (
  trans_type_key        BIGINT   COMMENT 'Transaction type identifier',
  txn_date_key          BIGINT     COMMENT 'Date Key of the transaction',
  txn_time_key          BIGINT   COMMENT 'Time-of-day key for the transaction',
  web_ord_num           BIGINT   COMMENT 'Athlete/web order number',
  txn_seq_number        STRING   COMMENT 'Sequence number of this txn within the order',
  dks_sku               BIGINT   COMMENT 'Product SKU code',
  units                 BIGINT   COMMENT 'Quantity in this transaction',
  tracking_number       STRING   COMMENT 'Fulfillment/tracking identifier',
  order_fulfill_number  BIGINT   COMMENT 'Composite order-fulfill number',
  estimated_ship_date   TIMESTAMP     COMMENT 'Estimated ship date',
  source_reason_cd      STRING   COMMENT 'Source reason code',
  decline_dttm          TIMESTAMP     COMMENT 'Decline timestamp (if any)',
  decline_unit          BIGINT   COMMENT 'Declined unit count',
  chain_key             BIGINT   COMMENT 'Store chain key',
  source_store_cd       STRING   COMMENT 'Source store code',


  date_last_modified    TIMESTAMP COMMENT 'Last modified in source system',
  modified_by           STRING  COMMENT 'Hard-coded value indicating update source: "OSOSilver"'  ,



  CONSTRAINT txn_order_sku_pk PRIMARY KEY   (
      txn_date_key,
      txn_time_key,
      web_ord_num,
      txn_seq_number,
      chain_key
    )
)
COMMENT 'Transaction-level detail per order-SKU, including decline/audit info'
CLUSTER BY ( web_ord_num, txn_seq_number, chain_key);