CREATE OR REPLACE VIEW ${ecom_apps_schema}.qlik_dim_ecom_order_header_vw
(
  ECOM_ORDER_HEADER_KEY,
  ECOM_OH_ORDER_SUBMIT_DATE_KEY,
  ECOM_OH_ORDER_SUBMIT_TIME_KEY,
  ECOM_OH_WEB_ORDER_NUMBER,
  ECOM_OH_AOS_STORE_KEY,
  ECOM_OH_PAYMENT_METHOD_KEY,
  ECOM_OH_LOYALTY_ID,
  ECOM_OH_BILL_STATE,
  ECOM_OH_BILL_ZIP,
  ECOM_OH_DEMAND_IND,
  ECOM_OH_ODS_RESHIP_CD,
  ECOM_OH_ORIG_WEB_ORDER_NUMBER,
  ECOM_OH_ORDER_SOURCE_CD,
  ECOM_OH_FRAUD_HOLD_FLG,
  ECOM_OH_EOM_FLG,
  ECOM_OH_TEST_ORDER_FLG,
  ECOM_OH_COMPLETE_DATE_KEY,
  ECOM_OH_ORDER_STATUS_KEY,
  OH_DATE_LAST_MODIFIED,
  ECOM_OH_CLK_FLG,
  ECOM_OH_ACTUAL_FF_CHANNEL_KEY,
  ECOM_OH_ACTUAL_FF_LOCATION_CNT,
  ECOM_OH_SCORECARD_ENTERED_FLG,
  WCS_DEVICE_TYPE_KEY,
  ECOM_PAYMENT_METHOD_KEY,
  ECOM_OH_LOYALTY_REWARD_USED,
  ECOM_OH_ACTUAL_STH_LOC_CNT
) AS
SELECT
  a.order_header_key,
  a.order_date_key AS ecom_order_submit_date_key,
  a.order_time_key AS ecom_order_submit_time_key,
  a.web_ord_num,
  a.aos_store_key,
  a.payment_method_key,
  a.scorecard_id,
  a.bill_state,
  SUBSTR(a.bill_zip, 1, 5) AS ecom_oh_bill_zip,
  NVL(a.demand_ind, 0) AS ecom_oh_demand_ind,
  CASE a.querystring_code WHEN 'RS' THEN 'RS' ELSE 'N' END as ecom_oh_ods_reship_cd,
  original_web_ord_num,
  CASE B.ORDER_SOURCE_CODE WHEN 'RESHIP' THEN 'CS' ELSE B.ORDER_SOURCE_CODE END AS ecom_oh_order_source_cd,
  NVL(fraud_hold_flg, 'N') AS ecom_oh_fraud_hold_flg,
  NVL(eoM_flg, 'N') AS ecom_oh_eom_flg,
  NVL(test_order_flg, 'N') AS ecom_oh_test_order_flg,
  order_complete_date_key,
  a.order_status_key,
  a.date_last_modified,
  clk_flg,
  NVL(a.actual_ff_channel_key, -1) AS ecom_oh_actual_ff_channel_key,
  A.ACTUAL_FF_LOCATION_CNT,
  CASE WHEN NVL(a.scorecard_id, 'N') = 'N' THEN 'N' ELSE 'Y' END AS ecom_oh_scorecard_entered_flg,
  a.device_Type_key,
  a.payment_method_key,
  NVL(reward_cert_used_Flg, 'N') AS ecom_oh_loyalty_reward_used,
  A.ACTUAL_sth_LOCATION_CNT
FROM prod_ecmde_db.ECOM_DIM.ORDER_HEADER AS a
LEFT JOIN prod_ecmde_db.ecom_dim.order_source_lkup AS b
  ON a.order_source_key = b.order_Source_key
WHERE order_date_key >= 20200202
