INSERT INTO ${ecom_schema}.CO_DO_BRIDGE_INCREMENTAL
(
  DISTRIBUTION_ORDER_NBR ,
    SCI_ORDER_ID ,
    MIN_PURCHASE_ORDER_ID ,
    CUSTOMER_ORDER_NBR ,
    PURCHASE_ORDERS_ID ,
    WEBSTORE ,
    CO_STATUS_ID  ,
    CO_STATUS_DESCRIPTION  ,
    ORDER_CONFIRMED_DATE ,
    IS_CO_CANCELLED  ,
    IS_PURCHASE_ORDERS_CONFIRMED ,
    INITIAL_ORDER_CREATE_DATE  ,
    ORDER_LAST_UPDATED_DATE  ,
    ORIGINAL_CUSTOMER_ORDER_NBR  ,
    DO_CREATE_DTTM ,
    DO_LAST_UPDATED_DTTM    
)
SELECT
    DISTRIBUTION_ORDER_NBR ,
    SCI_ORDER_ID ,
    MIN_PURCHASE_ORDER_ID ,
    CUSTOMER_ORDER_NBR ,
    PURCHASE_ORDERS_ID ,
    WEBSTORE ,
    CO_STATUS_ID  ,
    CO_STATUS_DESCRIPTION  ,
    ORDER_CONFIRMED_DATE ,
    IS_CO_CANCELLED  ,
    IS_PURCHASE_ORDERS_CONFIRMED ,
    INITIAL_ORDER_CREATE_DATE  ,
    ORDER_LAST_UPDATED_DATE  ,
    ORIGINAL_CUSTOMER_ORDER_NBR  ,
    DO_CREATE_DTTM ,
    DO_LAST_UPDATED_DTTM    
FROM ${ecom_schema}.VW_CO_DO_BRIDGE