CREATE OR REPLACE VIEW ${ecom_apps_schema}.qlik_intraday_orders
(
  ORDER_DATE_KEY,
  PRODUCT_ID,
  QUANTITY,
  EXTENDED_AMT,
  LINE_COST,
  SUBMIT_DT,
  WEBSTORE_KEY,
  UNIT_PRICE_AMT,
  FLASH_SALE,
  CLEARANCE_TYPE_KEY,
  BILL_TO_CITY,
  BILL_TO_STATE,
  BILL_TO_ZIP,
  ORDER_SOURCE_CODE,
  KIOSK_STORE_NUM,
  WEB_ORDER_NUM,
  CUST_REQ_FF_MODE_KEY,
  BOPIS_STORE_NUM,
  COMPLEX_PROMO_FLG,
  LOYALTY_DISCOUNT_FLG,
  PROMO_LIST,
  SW_PROMO_FLG,
  LINE_NUM,
  FRAUD_REVIEW_FLG,
  HOT_MARKET_FLG
) AS
SELECT
  CAST(DATE_FORMAT(submit_dt, 'yyyyMMdd') AS DOUBLE) AS order_date_key,
  dks_Sku_key AS product_id,
  quantity,
  extended_amt,
  line_cost,
  submit_dt,
  webstore_key,
  unit_price_amt,
  flash_sale,
  clearance_type_key,
  bill_to_city,
  bill_to_state,
  bill_to_zip,
  B.ORDER_SOURCE_CODE,
  kiosK_store_num,
  web_order_num,
  cust_fulfillment_mode_key,
  BOPIS_STORE,
  CASE WHEN complex_promo_cnt > 0 THEN 'Y' ELSE 'N' END AS complex_promo_flg,
  NVL(LOYALTY_DISCOUNT_FLG, 'N') AS loyalty_discount_flg,
  promo_list,
  NVL(SW_PROMO_FLG, 'N') AS sw_promo_flg,
  line_num,
  NVL(a.FRAUD_REVIEW_FLG, 'N') AS fraud_review_flg,
  CASE WHEN a.HOT_MARKET_FLG = 1 THEN 'Y' ELSE 'N' END AS hot_market_flg
FROM prod_ecmde_db.ecom_apps.nrt_order_rpt AS a
LEFT JOIN prod_ecmde_db.ECOM_DIM.ORDER_SOURCE_LKUP AS b
  ON a.order_source_key = b.order_source_key