CREATE TABLE ${ecom_dim_schema}.reason_newman (
  REASON_KEY BIGINT NOT NULL,
  REASON_CODE STRING NOT NULL,
  REASON_DESC STRING,
  REASON_CATEGORY_CODE STRING,
  REASON_CATEGORY_DESC STRING,
  REASON_GROUP_CODE STRING,
  REASON_GROUP_DESC STRING,
  TRANS_TYPE_KEY BIGINT NOT NULL DEFAULT -1,
  CHAIN_KEY BIGINT NOT NULL DEFAULT -1,
  DATA_SOURCE_KEY BIGINT NOT NULL DEFAULT -1,
  IS_CURRENT STRING NOT NULL DEFAULT 'C',
  DATE_FROM_KEY BIGINT NOT NULL DEFAULT -1,
  DATE_TO_KEY BIGINT NOT NULL DEFAULT -1,
  DATE_ADDED_SOURCE TIMESTAMP,
  DATE_MODIFIED_SOURCE TIMESTAMP,
  DATE_ADDED TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  ADDED_BY STRING NOT NULL DEFAULT current_user(),
  DATE_LAST_MODIFIED TIMESTAMP,
  MODIFIED_BY STRING,
  RECORD_STATUS STRING NOT NULL DEFAULT 'A',
  REFERENCE_ID BIGINT,
  CONSTRAINT reason_newman_pk PRIMARY KEY (REASON_KEY)
)
USING delta
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7');

insert into ${ecom_dim_schema}.reason_newman
(
    REASON_KEY,
    REASON_CODE,
    REASON_DESC,
    REASON_CATEGORY_CODE,
    REASON_CATEGORY_DESC,
    REASON_GROUP_CODE,
    REASON_GROUP_DESC,
    TRANS_TYPE_KEY,
    DATA_SOURCE_KEY,
    ADDED_BY
)
values
(
    360,
    '-530',
    'ADMIN_ABANDON',
    'CT',
    'CUSTOMER CHANGED MIND',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
),
(
    361,
    '-531',
    'ADMIN_ATHLETE_REQUEST',
    'CT',
    'CUSTOMER CHANGED MIND',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
),
(
    362,
    '-532',
    'ADMIN_FRAUD',
    'FP',
    'FRAUD / PAY AUTH',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
),
(
    363,
    '-533',
    'ADMIN_AGED_SLA',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    364,
    '-534',
    'ADMIN_OUT_OF_STOCK',
    'INV',
    'INVENTORY',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    365,
    '-535',
    'ADMIN_PRICING_PROMO_ISSUE',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    366,
    '-536',
    'ADMIN_QUALITY_ISSUE',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    367,
    '-537',
    'ADMIN_INCORRECT_PRODUCT',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    368,
    '-538',
    'ADMIN_TEST_ORDER',
    'CT',
    'CUSTOMER CHANGED MIND',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
),
(
    369,
    '-101',
    'ADMIN_STORE_PULLBACK',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    370,
    '-320',
    'ADMIN_CARRIER_REJECT',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    371,
    '-321',
    'ADMIN_INVALID_SHIPPING_ADDRESS',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    372,
    '-322',
    'ADMIN_MODIFICATION',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    373,
    '100',
    'NOT_FOUND',
    'INV',
    'INVENTORY',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    374,
    '109',
    'NO_ON_HAND',
    'INV',
    'INVENTORY',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    375,
    '110',
    'DAMAGE',
    'INV',
    'INVENTORY',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    376,
    '300',
    'UNSHIPPABLE_ADDRESS',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    377,
    '310',
    'PRICING_ISSUE',
    'OTH',
    'OTHER',
    'NCUST',
    'Retailer',
    3,
    23,
    session_user()
),
(
    378,
    '500',
    'FRAUD',
    'FP',
    'FRAUD / PAY AUTH',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
),
(
    379,
    '510',
    'ABANDON',
    'CT',
    'CUSTOMER CHANGED MIND',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
),
(
    380,
    '520',
    'ATHLETE_REQUEST',
    'CT',
    'CUSTOMER CHANGED MIND',
    'CUST',
    'Customer',
    3,
    23,
    session_user()
);